rgname   = "Omgithub-action"
location = "East US"
sname    = "demogithubactions"
vnet_name               = "dev-vnet"
vnet_address_space      = ["10.0.0.0/16"]
subnet_name             = "dev-subnet"
subnet_address_prefixes = ["10.0.1.0/24"]
pip_name                = "dev-pip"
nsg_name                = "dev-nsg"